l_english:
 SELECT_DIR: "Select $DIR$ directory"
 GAME_DIRS: "Game Installations"
 GAME_DIR: "$GAME$ installation directory"
 GAME_DIR_DESC: "The $GAME$ installation directory.\n\nNote that this should be the installation directory that contains the game executable and assets.\nNOT the user directory that contains your savegames and mods."
 STORAGE_DIR: "Storage directory"
 STORAGE_DIR_DESC: "The directory where the Pdx-Unlimiter stores all imported savegames."
 EU4SE: "Eu4SaveEditor"
 ENABLE_EU4SE: "Enable Eu4SaveEditor"
 EU4SE_DESC: "Specifies whether to enable the Eu4SaveEditor.\n\nIf you enable this, the Eu4SaveEditor will be downloaded and installed next time you start the Pdx-Unlimiter."
 MISC: "Miscellaneous"
 FONT_SIZE: "Font size"
 FONT_SIZE_DESC: "The font size within the app.\n\nIf you have a high display resolution, you can turn this up to increase readability."
 ENABLE_AUTO_UPDATE: "Enable auto update"
 ENABLE_AUTO_UPDATE_DESC: "Specifies whether to automatically update the Pdx-Unlimiter and its components when launching it."
 CONFIRM_DELETION: "Confirm deletion"
 CONFIRM_DELETION_DESC: "Specifies whether to ask for confirmation when deleting a campaign or savegame."
 START_STEAM: "Start steam"
 START_STEAM_DESC: "Specifies whether to start Steam when launching a game through the Pdx-Unlimiter.\n\nIf you disable this, Steam might not register your achievements while playing."
 DELETE_ON_IMPORT: "Delete on import"
 DELETE_ON_IMPORT_DESC: "Specifies whether to delete savegames after succesfully importing it into the Pdx-Unlimiter storage."
 RAKALY: "Rakaly.com"
 RAKALY_USER_ID: "User ID"
 RAKALY_USER_ID_DESC: "Your Rakaly.com User ID.\n\nYou can find this by going to the 'Account' page on Rakaly.com."
 RAKALY_API_KEY: "API key"
 RAKALY_API_KEY_DESC: "Your Rakaly.com API key.\n\nYou can generate an API key by going to the 'Account' page on Rakaly.com."
 SKANDERBEG: "Skanderbeg.pm"
 SKANDERBEG_API_KEY: "API key"
 SKANDERBEG_API_KEY_DESC: "Your Skanderbeg.pm API key.\n\nYou can find this by going to the 'API' page on Skanderbeg.pm."
 CONVERTERS: "Paradox Converters"
 CK3_TO_EU4: "CK3 to EU4 converter"
 CK3_TO_EU4_DESC: "The path to the CK3ToEU4 converter."
