l_russian:
 EDITOR_SETTINGS:0 "Настройки редактора"
 PERFORMANCE:0 "Производительность"
 SPACE:0 "Пробел"
 SPACES:0 "Пробелы"
 TAB:0 "Табуляция"
 TABS:0 "Табуляции"
 EXTERNAL_EDITOR:0 "Внешний редактор"
 EXTERNAL_EDITOR_DESC:0 "Внешний редактор, который будет использоваться при нажатии кнопки редактирования."
 SELECT_PROGRAM:0 "Выберите программу-редактор"
 INDENTATION:0 "Отступ"
 INDENTATION_DESC:0 "Символы отступа, которые будут использоваться при использовании внешнего редактора и всплывающих подсказок предварительного просмотра."
 PAGE_SIZE:0 "Размер страницы"
 PAGE_SIZE_DESC:0 "Количество нод, отображаемых на странице.\nЧем больше нод отображается, тем больше времени требуется для загрузки новых нод."
 MAX_TOOLTIP_LINES:0 "Максимальное количество строк в тултипе"
 MAX_TOOLTIP_LINES_DESC:0 "Максимальное количество строк тултипа превью ноды."
 ENABLE_NODE_TAGS:0 "Включить теги нод"
 ENABLE_NODE_TAGS_DESC:0 "Теги нод снижают производительность, поскольку необходимо анализировать каждую ноду, чтобы определить её тег для отображения."
 ENABLE_NODE_JUMPS:0 "Включить переходы между нодами"
 ENABLE_NODE_JUMPS_DESC:0 "Переходы между нодами снижают производительность, поскольку необходимо анализировать каждую ноду, чтобы определить, куда следует перейти."
 WARN_ON_TYPE_CHANGE:0 "Предупреждать об изменении типа"
 WARN_ON_TYPE_CHANGE_DESC:0 "Отображение предупреждения при изменении типа данных записи, поскольку обычно это не предусмотрено."
 EXTERNAL_EDITOR_WAIT_INTERVAL:0 "Время ожидания перезагрузки внешнего редактора (мс)"
 EXTERNAL_EDITOR_WAIT_INTERVAL_DESC:0 "При сохранении отредактированного файла с помощью внешнего редактора, Pdx-Unlimiter ожидает указанное количество времени, пока не начнёт читать файл. Это может быть полезно для предотвращения ошибок, вызванных слишком ранним чтением файла, если вы используете медленный жесткий диск."