l_russian:
 SETTINGS:0 "Настройки"
 INTERFACE:0 "Интерфейс"
 GENERAL:0 "Общее"
 IMPORTS:0 "Импорт"
 IRONY:0 "Менеджер модов Irony"
 USE_GAME_LANGUAGE:0 "Использовать язык игры"
 MAX_TOOLTIP_SIZE:0 "Максимальная ширина всплывающей подсказки"
 MAX_TOOLTIP_SIZE_DESC:0 "Максимальная ширина всплывающих подсказок предварительного просмотра нод в пикселях."
 USE_GAME_LANGUAGE_DESC:0 "Всегда используйте язык текущей выбранной игры.\nЕсли этот параметр включен, настройка пользовательского языка ниже не используется. Обратите внимание, что переводы неполные!"
 LANGUAGE:0 "Язык"
 LANGUAGE_DESC:0 "Используемый пользовательский язык интерфейса.\nПрименяется только в том случае, если для параметра «Использовать язык игры» установлено значение false."
 SELECT_DIR:0 "Выберите каталог $DIR$"
 CHOICE_VALUE_ERROR:0 "Значение $VAL$ недопустимо. Сброс до значения по умолчанию."
 GAME_DIRS:0 "Каталоги установленных игр"
 GAME_DIR_ERROR:0 "Произошла ошибка при загрузке вашей игры $GAME$"
 GAME_DIR_ERROR_MSG:0 "Поддержка $GAME$ отключена. Если вы считаете, что папка вашей игры валидна,\nпроверьте, правильно ли указан каталог установки."
 GAME_DIR:0 "Каталог установки $GAME$"
 GAME_DIR_DESC:0 "Каталог установки $GAME$.\n\nОбратите внимание, что это должен быть установочный каталог, содержащий исполняемый файл игры и её ассеты.\nНЕ пользовательский каталог, содержащий ваши сохранения и моды."
 STORAGE_DIR:0 "Каталог хранения"
 STORAGE_DIR_DESC:0 "Каталог, в котором Pdx-Unlimiter хранит все импортированные сохранения.\nОбратите внимание, что он совершенно не относится к каталогам сохранений ваших игр Paradox!"
 STORAGE_DIR_DIALOG_TITLE:0 "Подтвердить перемещение хранилища"
 STORAGE_DIR_DIALOG_TEXT:0 "Вы пытаетесь переместить хранилище сохраненных игр из $FROM$\nв $TO$.\nЭто приведет к перемещению всех файлов сохраненных игр и может занять некоторое время."
 STORAGE_DIR_SAVEGAME_WARNING_TITLE:0 "Невернsq каталог внутреннего хранилища"
 STORAGE_DIR_SAVEGAME_WARNING_TEXT:0 "Каталог, который вы выбрали в качестве внутреннего хранилища Pdx-Unlimiter, выглядит как каталог сохранения игры.\nОбратите внимание, что внутреннее хранилище Pdx-Unlimiter не связано с каталогами сохранения игр Paradox.\n"
 STORAGE_DIR_RESET_TITLE:0 "Каталог хранилища не существует"
 STORAGE_DIR_RESET_TEXT:0 "Каталог хранения $PATH$ не существует или больше недействителен!\nВы хотите сбросить его на каталог по умолчанию?"
 STORAGE_DIR_INVALID_TITLE:0 "Каталог хранилища не существует"
 STORAGE_DIR_INVALID_TEXT:0 "Каталог хранения $PATH$ не существует или недействителен."
 EU4SE:0 "OsaSaveEditor"
 ENABLE_EU4SE:0 "Включить OsaSaveEditor"
 ENABLE_EU4SE_DESC:0 "Указывает, включать ли OsaSaveEditor.\n\nЕсли вы включите это, OsaSaveEditor будет загружен и установлен при следующем запуске Pdx-Unlimiter."
 MISC:0 "Разное"
 FONT_SIZE:0 "Размер шрифта"
 FONT_SIZE_DESC:0 "Размер шрифта в приложении.\n\nЕсли у вас высокое разрешение экрана, вы можете увеличить его, чтобы улучшить читаемость."
 ENABLE_AUTOUPDATE:0 "Включить автоматическое обновление"
 ENABLE_AUTOUPDATE_DESC:0 "Указывает, следует ли автоматически обновлять Pdx-Unlimiter и его компоненты при запуске."
 CONFIRM_DELETION:0 "Подтвердить удаление"
 CONFIRM_DELETION_DESC:0 "Указывает, запрашивать ли подтверждение при удалении кампании или сохранения."
 START_STEAM:0 "Запустить через Steam"
 START_STEAM_DESC:0 "Указывает, следует ли запускать Steam при запуске игры через Pdx-Unlimiter.\n\nЕсли вы отключите это, Steam может не регистрировать получение достижений во время игры."
 DELETE_ON_IMPORT:0 "Удалить оригинал после импорта"
 DELETE_ON_IMPORT_DESC:0 "Указывает, следует ли удалять сохраненные игры после их успешного импорта в хранилище Pdx-Unlimiter."
 SKANDERBEG:0 "Skanderbeg.pm"
 SKANDERBEG_API_KEY:0 "Ключ API"
 SKANDERBEG_API_KEY_DESC:0 "Ваш ключ API Skanderbeg.pm.\n\nВы можете найти его, перейдя на страницу «API» на Skanderbeg.pm."
 CONVERTERS:0 "Конвертеры Paradox"
 CK3_TO_EU4_DIR:0 "Конвертер CK3 в EU4"
 CK3_TO_EU4_DIR_DESC:0 "Путь к конвертеру CK3ToEU4."
 IRONY_DIR:0 "Место установки"
 IRONY_DIR_DESC:0 "Местоположение вашей установки Irony."
 LAUNCH_IRONY:0 "Запустить Irony"
 LAUNCH_IRONY_DESC:0 "Запускает менеджер модов Irony вместо Paradox Launcher."
 TIMED_IMPORTS:0 "Включен синхронизированный импорт"
 TIMED_IMPORTS_DESC:0 "Включает автоматический импорт последней сохраненной игры по прошествии определенного времени во время игры."
 TIMED_IMPORTS_INTERVAL:0 "Минуты между импортами"
 TIMED_IMPORTS_INTERVAL_DESC:0 "Интервал между автоматическими импортами в минутах."
 THIRD_PARTY_ERROR:0 "Поддержка $APP$ отключена.\nЕсли вы считаете, что папка приложения валидна,\nпроверьте, правильно ли указан каталог установки.\n"
 PLAY_SOUND_ON_BACKGROUND_IMPORT:0 "Воспроизведение звука при фоновом импорте"
 PLAY_SOUND_ON_BACKGROUND_IMPORT_DESC:0 "Воспроизведение звукового сигнала при импорте сохраненной игры, когда игра открыта, а Pdx-Unlimiter работает в фоновом режиме."
 XBOX_UNAVAILABLE:0 "Эта игра распространяется через Windows Store."
 XBOX_DIST_BUTTON:0 "Выберите каталог Windows Store.\nЭто сработает, только если у вас установлена ​​версия игры из Windows Store."
 CLEAR_DIST_BUTTON:0 "Очистить дистрибутив выбранной игры."
 BROWSE_DIST_BUTTON:0 "Укажите каталог установки вручную."
 IMPORT_ON_NORMAL_GAME_EXIT:0 "Импортировать при выходе из игры"
 IMPORT_ON_NORMAL_GAME_EXIT_DESC:0 "Автоматически импортировать последнюю сохраненную игру при обычном выходе из игры, т. е. когда не используются какие-либо фишки сейвскамминга."