name="Everyone hates the HRE"
description="a"
long_description=""
archive_name="challenge_destroy_hre.zip"
start_tags={
    "FRA"
    "DEN"
}
words={
	"Historical"
	"New Nations"
	"Map"
	"Gameplay"
	"Expansion"
	"Religion"
	"Technologies"
	"National Ideas"
	"Events"
	"Missions And Decisions"
}
supported_version="1.27.*.*"