name: Build

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-20.04,
          # macos-10.15,
          windows-2022
        ]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.3.0'
          java-version: '17'
      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME
      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Execute dist build
        run: ./gradle/gradlew --info createDist

      - name: JReleaser Release
        run: ./gradle/gradlew jreleaserRelease
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
          JRELEASER_DISCORD_WEBHOOK: ${{ secrets.JRELEASER_DISCORD_WEBHOOK }}
        if: ${{ github.event_name != 'pull_request' }}

      - name: JReleaser Announce
        run: ./gradle/gradlew jreleaserAnnounce
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
          JRELEASER_DISCORD_WEBHOOK: ${{ secrets.JRELEASER_DISCORD_WEBHOOK }}
        if: ${{ matrix.os == 'windows-2022' && github.event_name != 'pull_request' }}

      - name: unzip artifact for windows
        run: unzip build/pdx_unlimiter-windows.zip -d build/pdx_unlimiter-windows || true
      - name: unzip artifact for linux
        run: unzip build/pdx_unlimiter-linux.zip -d build/pdx_unlimiter-linux || true
      - name: unzip artifact for mac
        run: unzip build/pdx_unlimiter-mac.zip -d build/pdx_unlimiter-mac || true

      - name: Upload mac dist as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: pdx_unlimiter-mac-dev
          path: build/pdx_unlimiter-mac
          if-no-files-found: ignore

      - name: Upload Windows dist as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: pdx_unlimiter-windows-dev
          path: build/pdx_unlimiter-windows
          if-no-files-found: ignore

      - name: Upload Linux dist as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: pdx_unlimiter-linux-dev
          path: build/pdx_unlimiter-linux
          if-no-files-found: ignore
